# Generated by Django 4.0 on 2022-01-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='نام')),
                ('lastname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('marital_status', models.IntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], verbose_name='وضعیت تاهل')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل سکونت')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('birthday', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('Requested_rights', models.IntegerField(verbose_name='حقوق درخواستی')),
                ('intrested_job', models.CharField(max_length=100, verbose_name='شغل مورد علاقه')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
            },
        ),
    ]
