# Generated by Django 4.0 on 2022-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='Requested_rights',
            new_name='Expected_Salary',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
    ]
