# Generated by Django 4.0 on 2022-01-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='profile_image',
            new_name='profileimage',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='lastname',
        ),
    ]
