# Generated by Django 4.0 on 2022-01-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_profile_image_profilemodel_profileimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
