# Generated by Django 4.0 on 2022-01-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profilemodel_profileimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='marital_status',
        ),
    ]
