# Generated by Django 4.0 on 2022-01-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profilemodel_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'مجرد'), (2, 'متاهل')], null=True, verbose_name='وضعیت تاهل'),
        ),
    ]
