# Generated by Django 4.0 on 2022-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profilemodel_coursesname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='coursesname',
            field=models.CharField(max_length=300, null=True, verbose_name='نام دوره آموزشی'),
        ),
    ]
