# Generated by Django 4.0 on 2022-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_profilemodel_coursesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofarticle',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofaward',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofproject',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='end_time',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='start_time',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
    ]
