# Generated by Django 4.0 on 2022-01-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_profilemodel_dateofarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='from_year',
            field=models.IntegerField(null=True, verbose_name='سال شروع'),
        ),
    ]
