# Generated by Django 4.0 on 2022-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_profilemodel_from_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofarticle',
            field=models.IntegerField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofaward',
            field=models.IntegerField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='dateofproject',
            field=models.IntegerField(null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='end_time',
            field=models.IntegerField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='start_time',
            field=models.IntegerField(null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='to_year',
            field=models.IntegerField(null=True, verbose_name='سال پایان'),
        ),
    ]
