# Generated by Django 4.0 on 2022-02-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_profilemodel_dateofarticle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='levelofskill',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='skillname',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='skillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_area', models.CharField(max_length=100, null=True, verbose_name='حوزه کاری')),
                ('skillname', models.CharField(max_length=100, verbose_name='مهارت')),
                ('levelofskill', models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'متوسط'), (3, 'پیشرفته')], verbose_name='سطح مهارت')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'مهارت ها',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
    ]
