# Generated by Django 4.0 on 2022-02-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_profilemodel_levelofskill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='coursesname',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='skillsmodel',
            name='skill_area',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='coursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursesname', models.CharField(max_length=300, verbose_name='نام دوره آموزشی')),
                ('institute', models.CharField(max_length=300, verbose_name='نام آموزشگاه')),
                ('certificate', models.URLField(blank=True, null=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'دوره های آموزشی',
                'verbose_name_plural': 'دوره های آموزشی',
            },
        ),
    ]
