# Generated by Django 4.0 on 2022-02-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_profilemodel_coursesname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='article_title',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='award_title',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='dateofarticle',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='dateofaward',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='dateofproject',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='leveloflanguage',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='project_title',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='article',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='award',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='project',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='projectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('dateofproject', models.TimeField(verbose_name='سال')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'پروژه ها و تجربیات آکادمیک',
                'verbose_name_plural': 'پروژه ها و تجربیات آکادمیک',
            },
        ),
        migrations.CreateModel(
            name='languagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='زبان')),
                ('leveloflanguage', models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'پایین تر از متوسط'), (3, 'متوسط'), (4, 'بالاتر از متوسط'), (5, 'پیشرفته'), (6, 'زبان مادری')], verbose_name='سطح مهارت')),
                ('languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'زبان ها',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.CreateModel(
            name='awardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('dateofaward', models.TimeField(verbose_name='سال')),
                ('awards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'جوایزو افتخارات',
                'verbose_name_plural': 'جوایزو افتخارات',
            },
        ),
        migrations.CreateModel(
            name='articlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('dateofarticle', models.TimeField(verbose_name='سال')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'کتاب ها و مقالات',
                'verbose_name_plural': 'کتاب ها و مقالات',
            },
        ),
    ]
