# Generated by Django 4.0 on 2022-02-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_profilemodel_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='major',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='to_year',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='university',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='aducation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='workexperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_area', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغل')),
                ('company_name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('start_time', models.TimeField(verbose_name='تاریخ شروع')),
                ('end_time', models.TimeField(verbose_name='تاریخ پایان')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'سوابق شغلی',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
        migrations.CreateModel(
            name='aducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.IntegerField(choices=[(1, 'Associate'), (2, 'Bachelor of science'), (3, 'Master of science '), (4, 'phD')], verbose_name='مقطع تحصیلی')),
                ('major', models.CharField(max_length=100, verbose_name='رشته تحصیلی')),
                ('university', models.CharField(max_length=100, verbose_name='دانشگاه')),
                ('gpa', models.FloatField(verbose_name='معدل')),
                ('from_year', models.DateField(verbose_name='سال شروع')),
                ('to_year', models.DateField(verbose_name='سال پایان')),
                ('aducations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'سوابق تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
    ]
