# Generated by Django 4.0 on 2022-02-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_profilemodel_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='aducation',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='article',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='award',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='skill',
        ),
    ]
