# Generated by Django 4.0 on 2022-02-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_aducationmodel_from_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aducationmodel',
            name='from_yearr',
        ),
        migrations.RemoveField(
            model_name='aducationmodel',
            name='to_yearr',
        ),
        migrations.AddField(
            model_name='aducationmodel',
            name='from_year',
            field=models.DateField(null=True, verbose_name='سال شروع'),
        ),
        migrations.AddField(
            model_name='aducationmodel',
            name='to_year',
            field=models.DateField(null=True, verbose_name='سال پایان'),
        ),
    ]
