# Generated by Django 4.0 on 2022-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_aducationmodel_from_yearr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='end_time',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='start_time',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
