# Generated by Django 4.0 on 2022-02-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_workexperiencemodel_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperiencemodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workexperiencemodel',
            name='start_time',
        ),
    ]
