# Generated by Django 4.0 on 2022-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_workexperiencemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencemodel',
            name='end_time',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='workexperiencemodel',
            name='start_time',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
    ]
