# Generated by Django 4.0 on 2022-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_workexperiencemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='dateofarticle',
            field=models.DateField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='dateofaward',
            field=models.DateField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='dateofproject',
            field=models.DateField(verbose_name='سال'),
        ),
    ]
