# Generated by Django 4.0 on 2022-02-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_articlesmodel_dateofarticle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='dateofarticle',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
        migrations.AddField(
            model_name='awardsmodel',
            name='award_title',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='awardsmodel',
            name='dateofaward',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='dateofproject',
            field=models.DateField(null=True, verbose_name='سال'),
        ),
    ]
