# Generated by Django 4.0 on 2022-02-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_articlesmodel_dateofarticle_awardsmodel_award_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='awardsModel',
        ),
    ]
