# Generated by Django 4.0 on 2022-02-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_awardsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='awardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('dateofaward', models.DateField(verbose_name='سال')),
                ('awards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilemodel')),
            ],
            options={
                'verbose_name': 'جوایزو افتخارات',
                'verbose_name_plural': 'جوایزو افتخارات',
            },
        ),
    ]
