# Generated by Django 4.0 on 2022-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_skillsmodel_levelofskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsmodel',
            name='levelofskill',
            field=models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'متوسط'), (3, 'پیشرفته')], null=True, verbose_name='سطح مهارت'),
        ),
    ]
