# Generated by Django 4.0 on 2022-04-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_skillsmodel_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'profiles', 'verbose_name_plural': 'profiles'},
        ),
    ]
