# Generated by Django 4.0 on 2021-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmemodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
