# Generated by Django 4.0 on 2021-12-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resumesite', '0002_aboutmemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='aboutmemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='auth.user'),
        ),
    ]
