# Generated by Django 4.0.1 on 2022-01-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0003_remove_aboutmemodel_username_aboutmemodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmemodel',
            name='owner',
        ),
    ]
