# Generated by Django 4.0 on 2022-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0005_aboutmemodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='aducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.IntegerField(choices=[(1, 'کاردانی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکترا')], verbose_name='مقطع تحصیلی')),
                ('major', models.CharField(max_length=100, verbose_name='مقطع تحصیلی')),
                ('university', models.CharField(max_length=100, verbose_name='دانشگاه')),
                ('gpa', models.FloatField(verbose_name='معدل')),
                ('from_year', models.DateField(verbose_name='سال شروع')),
                ('to_year', models.DateField(verbose_name='سال پایان')),
            ],
        ),
    ]
