# Generated by Django 4.0 on 2022-01-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0006_aducationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=500, verbose_name='عنوان')),
                ('dateofarticle', models.TimeField(verbose_name='سال')),
            ],
            options={
                'verbose_name': 'کتاب ها و مقالات',
                'verbose_name_plural': 'کتاب ها و مقالات',
            },
        ),
        migrations.CreateModel(
            name='awardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('dateofaward', models.TimeField(verbose_name='سال')),
            ],
            options={
                'verbose_name': 'جوایزو افتخارات',
                'verbose_name_plural': 'جوایزو افتخارات',
            },
        ),
        migrations.CreateModel(
            name='coursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursesname', models.CharField(max_length=300, verbose_name='نام دوره آموزشی')),
                ('institute', models.CharField(max_length=300, verbose_name='نام آموزشگاه')),
            ],
            options={
                'verbose_name': 'دوره های آموزشی',
                'verbose_name_plural': 'دوره های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='languagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='زبان')),
                ('leveloflanguage', models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'پایین تر از متوسط'), (3, 'متوسط'), (4, 'بالاتر از متوسط'), (5, 'پیشرفته'), (6, 'زبان مادری')], verbose_name='سطح مهارت')),
            ],
            options={
                'verbose_name': 'زبان ها',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.CreateModel(
            name='projectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('dateofproject', models.TimeField(verbose_name='سال')),
            ],
            options={
                'verbose_name': 'پروژه ها و تجربیات آکادمیک',
                'verbose_name_plural': 'پروژه ها و تجربیات آکادمیک',
            },
        ),
        migrations.CreateModel(
            name='skillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100, verbose_name='مهارت')),
                ('levelofskill', models.IntegerField(choices=[(1, 'مقدماتی'), (2, 'متوسط'), (3, 'پیشرفته')], verbose_name='سطح مهارت')),
            ],
            options={
                'verbose_name': 'مهارت ها',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='workexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغل')),
                ('company_name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('start_time', models.TimeField(verbose_name='تاریخ شروع')),
                ('end_time', models.TimeField(verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'سوابق شغلی',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutmemodel',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterModelOptions(
            name='aducationmodel',
            options={'verbose_name': 'سوابق تحصیلی', 'verbose_name_plural': 'سوابق تحصیلی'},
        ),
    ]
