# Generated by Django 4.0 on 2022-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0007_articlesmodel_awardsmodel_coursesmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='coursesname',
            field=models.CharField(default='a', max_length=300, verbose_name='نام دوره آموزشی'),
        ),
    ]
