# Generated by Django 4.0 on 2022-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0008_alter_coursesmodel_coursesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='coursesname',
            field=models.CharField(max_length=300, verbose_name='نام دوره آموزشی'),
        ),
    ]
