# Generated by Django 4.0 on 2022-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0009_alter_coursesmodel_coursesname'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmemodel',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
